apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    ingressclass.kubernetes.io/is-default-class: "true"
  name: nginx-route-edu18
spec:
  host: nginx
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: mynginx
    weight: 100
  wildcardPolicy: None
